# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sw2at 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "sw2at"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Vitaly Tarasenko"]
  s.date = "2015-06-21"
  s.description = " Define your Test World strategies, use SW2AT UI for managing tests revisions. "
  s.email = "vetal.tarasenko@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sw2at.rb",
    "lib/swat/rspec_setup.rb",
    "sw2at.gemspec"
  ]
  s.homepage = "http://github.com/tw4qa/sw2at"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "SW2AT - Simple Way to Automate Tests."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sw2at-capybara>, ["~> 0.0.1"])
      s.add_runtime_dependency(%q<sw2at-tw>, ["~> 0.0.1"])
      s.add_runtime_dependency(%q<sw2at-ui>, ["~> 0.0.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<sw2at-capybara>, ["~> 0.0.1"])
      s.add_dependency(%q<sw2at-tw>, ["~> 0.0.1"])
      s.add_dependency(%q<sw2at-ui>, ["~> 0.0.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<sw2at-capybara>, ["~> 0.0.1"])
    s.add_dependency(%q<sw2at-tw>, ["~> 0.0.1"])
    s.add_dependency(%q<sw2at-ui>, ["~> 0.0.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

